version: '3'
services:
  customer-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: mateusrfiuza/customer-api
    container_name: customer-api
    ports:
      - '8080:8080'
    networks:
      - production-network
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "challenge"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - production-network
volumes:
  container-volume:
networks:
  production-network:
    driver: bridge