version: '3'
services:
  customer-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: mateusrfiuza/customer-api
    container_name: customer-api
    ports:
      - '8080:8080'
    networks:
      - production-network
    links:
      - postgres
      - redis
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - production-network
volumes:
  container-volume:
networks:
  production-network:
    driver: bridge