version: '3'
services:
  location-services:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: mateusrfiuza/client-api
    container_name: client-api
    ports:
      - '8080:8080'
    networks:
      - production-network
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "challenge"
    ports:
      - "3306:3306"
    volumes:
      - .init.sql:/docker-entrypoint-initdb.d/.init.sql
    networks:
      - production-network
volumes:
  container-volume:
networks:
  production-network:
    driver: bridge