CREATE TABLE IF NOT EXISTS CHALLENGE.CLIENT (
   id UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email  VARCHAR(255) NOT NULL,
   CONSTRAINT EMAIL_UK01 UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS EMAIL_IDX01 ON CHALLENGE.CLIENT(email);
