main.banner-mode: off
spring:
    r2dbc:
      url: r2dbc:pool:postgres://db:5432/postgres?schema=challenge
      username: postgres
      password: admin
      max-idle: 30m
      validation-query: Select 1

product-api:
  url: http://challenge-api.luizalabs.com
